amazon:
    aws:
        accesskey: fakekey
        secretkey: fakesecretkey
    dynamodb:
        endpoint: http://localhost:8000
debug: true
management:
    health:
        consul:
            enabled: false
    security:
        enabled: false
server:
    port: 8005
    servlet:
        context-path: /qbthonEvents-emailservice
spring:
    application:
        name: qbthonEvents-emailservice
    mail:
        host: smtp.gmail.com
        password: Dont4Get
        port: 465
        properties:
            mail:
                debug: true
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    socketFactory:
                        class: javax.net.ssl.SSLSocketFactory
                        port: 465
                    starttls:
                        enable: true
                    timeout: 5000
                    writetimeout: 5000
                transport:
                    protocol: smtp
        username: sukanyaram2012@gmail.com